Change run-ansible to not rely on submodules anymore

diff --git a/run-ansible b/run-ansible
--- a/run-ansible
+++ b/run-ansible
@@ -12,6 +12,9 @@ shopt -s nullglob
 cd "$(dirname "$0")"
 
 
+readonly ANSIBLE_TAG="v2.9.15"
+readonly ANSIBLE_REPO_URL="https://github.com/ansible/ansible.git"
+
 readonly ANSIBLE_SETUP_PATH="ansible-setup"
 
 readonly HOMEBREW_TARGET_DIR=".cache/homebrew"
@@ -21,9 +24,9 @@ readonly LOCAL_BREW_INSTALL_SCRIPT="$ANSIBLE_SETUP_PATH/roles/bin/files/bash/loc
 # ¡¡¡RELATIVE TO ANSIBLE_SETUP_PATH!!! #
 readonly VAULT_ID_PATH="../.cache/.vault-id"
 
-readonly DEPENDENCIES_DIR="dependencies"
-readonly ANSIBLE_REQUIREMENTS_PATH="$DEPENDENCIES_DIR/ansible/requirements.txt"
-readonly ANSIBLE_ENV_SETUP="$DEPENDENCIES_DIR/ansible/hacking/env-setup"
+readonly ANSIBLE_TARGET_DIR=".cache/ansible"
+readonly ANSIBLE_REQUIREMENTS_PATH="$ANSIBLE_TARGET_DIR/requirements.txt"
+readonly ANSIBLE_ENV_SETUP="$ANSIBLE_TARGET_DIR/hacking/env-setup"
 
 readonly VIRTUALENV_TARGET_DIR=".cache/virtualenv"
 readonly VIRTUALENV_ACTIVATE="$VIRTUALENV_TARGET_DIR/bin/activate"
@@ -35,9 +38,9 @@ usage() {
 	echo "usage: run-ansible [options] [roles...]"
 	echo
 	echo "Supported options:"
-	echo "   -f/--force   force the reinstallation of the virtualenv"
-	echo "   -h/--help    show the help and exit"
-	echo "   -v/--verbose (repeat up to four times for more verbosity)"
+	echo "   -i/--install   force the reinstallation/update of ansible and the virtualenv"
+	echo "   -h/--help      show the help and exit"
+	echo "   -v/--verbose   (repeat up to four times for more verbosity)"
 	echo
 	echo "Choosing the Ansible module to run:"
 	echo "   -m/--module ansible_module   which Ansible module to run (default \"playbook\")"
@@ -66,13 +69,13 @@ usage() {
 
 
 ROLES=
-FORCE=0
+INSTALL=0
 VERBOSE=0
 EXTRA_ARGS=()
 ANSIBLE_MODULE="playbook"
 while [ $# -gt 0 ]; do
 	case "$1" in
-		--force   | -f) FORCE=1;;
+		--install | -i) INSTALL=1;;
 		--verbose | -v) VERBOSE=$((VERBOSE + 1));;
 		-vv)            VERBOSE=$((VERBOSE + 2));;
 		-vvv)           VERBOSE=$((VERBOSE + 3));;
@@ -135,10 +138,19 @@ if [ ! -x "$LOCAL_BREW_INSTALL_SCRIPT" ]; then
 	exit 1
 fi
 
-if [ ! -e "$ANSIBLE_ENV_SETUP" ]; then
-	echo "Not found: $ANSIBLE_ENV_SETUP" >/dev/stderr
-	echo "Did you forget to 'git submodule update --init --recursive'?" >/dev/stderr
-	exit 1
+# Ansible installation
+if [ ! -e "$ANSIBLE_ENV_SETUP" -o "$INSTALL" != 0 ]; then
+	echo "Ansible not found in cache, or installation forced: cloning it" >"$DEV_NULL"
+	test -d "$ANSIBLE_TARGET_DIR" || git clone --depth=1 "$ANSIBLE_REPO_URL" "$ANSIBLE_TARGET_DIR"
+	(
+		cd "$ANSIBLE_TARGET_DIR"
+		git fetch -Pt
+		git checkout "$ANSIBLE_TAG"
+	)
+	if [ ! -e "$ANSIBLE_ENV_SETUP" ]; then
+		echo "Ansible not found in cache even after instllation; something is wrong…" >/dev/stderr
+		exit 1
+	fi
 fi
 
 # We need python3. If it is installed in the system, the local brew install
@@ -154,10 +166,11 @@ if ! command -v python3 >/dev/null; then
 fi
 
 # Virtualenv installation
-if [[ ! -e "$VIRTUALENV_ACTIVATE" || "$FORCE" != 0 ]]; then
+if [[ ! -e "$VIRTUALENV_ACTIVATE" || "$INSTALL" != 0 ]]; then
+	echo "Installing virtualenv" >"$DEV_NULL"
 	python3 -m venv "$VIRTUALENV_TARGET_DIR" >"$DEV_NULL"
 elif [ -e "$VIRTUALENV_ACTIVATE" ]; then
-	echo "Skipping virtualenv install (already exists); use --force to override" >"$DEV_NULL"
+	echo "Skipping virtualenv install (already exists); use --install to override" >"$DEV_NULL"
 fi
 
 # Activate virtualenv
@@ -196,7 +209,7 @@ popd >/dev/null 2>&1
 # I don’t really like hidding all output from a program, but this one prints a
 # useless warning on macOS on stderr, so I silence it!
 # shellcheck disable=SC1090
-source "$DEPENDENCIES_DIR/ansible/hacking/env-setup" &>"$DEV_NULL"
+source "$ANSIBLE_ENV_SETUP" &>"$DEV_NULL"
 
 readonly HOST_OS="$(uname)"
 readonly ANSIBLE_VERBOSE_OPTION="${VERBOSE+-$(printf 'v%.0s' $(seq $VERBOSE))}"
